// <auto-generated />
using AplikacjaDoNaukiJęzyków.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AplikacjaDoNaukiJęzyków.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AplikacjaDoNaukiJęzyków.Models.Slowo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("PoziomSlowa")
                        .HasColumnType("text");

                    b.Property<string>("SlowoAng")
                        .HasColumnType("text");

                    b.Property<string>("SlowoAra")
                        .HasColumnType("text");

                    b.Property<string>("SlowoPol")
                        .HasColumnType("text");

                    b.Property<string>("SlowoUkr")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Slowa");
                });
#pragma warning restore 612, 618
        }
    }
}
