// <auto-generated />
using AplikacjaDoNaukiJęzyków.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AplikacjaDoNaukiJęzyków.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AplikacjaDoNaukiJęzyków.Models.Slowo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("PoziomSlowa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoAng")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoAra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoPol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlowoUkr")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Slowa");
                });
#pragma warning restore 612, 618
        }
    }
}
